[package]
name = "k3s-proxmox-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
clap = { version = "4.5.9", features = ["derive"] }
network-interface = "2.0.0"
once_cell = "1.19.0"
openssl = "0.10.66"
tokio = { version = "1.38.1", features = ["full"] }
